(()=>{
  const R=window.SR=window.SR||{};
  const pick=a=>a[Math.random()*a.length|0];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  R.pick=pick; R.clamp=clamp;

  R.HULLS=[
    ['Starfighter',2,2,1,220,90,0,0,0],
    ['Heavy Fighter',3,3,1,340,130,1,0,900],
    ['Gunship',4,4,2,520,190,1,0,2400],
    ['Corvette',6,5,2,800,280,2,1,5200],
    ['Light Frigate',9,7,3,1250,430,3,2,11000],
    ['Frigate',12,9,4,1900,650,4,3,22000],
    ['Heavy Frigate',16,12,4,2850,930,5,4,42000]
  ].map((x,i)=>({id:'hull.'+i,name:x[0],crew:x[1],weapons:x[2],active:x[3],hp:x[4],shield:x[5],drones:x[6],escorts:x[7],cost:x[8],tier:i}));

  R.WEAPONS=[
    {id:'weapon.autocannon',family:'autocannon',name:'Autocannon',icon:'»',color:'#ffb15f',damage:10,rate:7.2,range:540,cost:0,minHull:0,desc:'Rapid kinetic fire that chews through light ships.',kind:'rapid'},
    {id:'weapon.railgun',family:'railgun',name:'Railgun',icon:'→',color:'#ffffff',damage:92,rate:.62,range:980,cost:650,minHull:1,desc:'Slow, brutal shots that punch through several targets.',pierce:4,kind:'pierce'},
    {id:'weapon.pulse',family:'pulse',name:'Pulse Laser',icon:'━',color:'#62dcff',damage:15,rate:3.5,range:690,cost:0,minHull:0,desc:'Reliable energy bursts with excellent tracking.',burst:2,kind:'burst'},
    {id:'weapon.beam',family:'beam',name:'Beam Lance',icon:'═',color:'#a6f7ff',damage:27,rate:1.4,range:850,cost:950,minHull:2,desc:'A precise lance that cuts a line through clustered ships.',pierce:2,kind:'beam'},
    {id:'weapon.plasma',family:'plasma',name:'Plasma Mortar',icon:'♨',color:'#ff6bd7',damage:58,rate:.85,range:650,cost:1200,minHull:2,desc:'Lobs unstable plasma that detonates in a wide blast.',aoe:72,slow:true,kind:'mortar'},
    {id:'weapon.ion',family:'ion',name:'Ion Arc',icon:'⚡',color:'#89aaff',damage:19,rate:1.7,range:620,cost:1400,minHull:3,desc:'Strips shields and jumps electrical damage between nearby ships.',ion:true,chain:2,kind:'chain'},
    {id:'weapon.missile',family:'missile',name:'Missile Rack',icon:'⌁',color:'#ff9d79',damage:48,rate:.9,range:1000,cost:1800,minHull:3,desc:'Launches homing warheads that explode on impact.',homing:true,aoe:58,kind:'homing'},
    {id:'weapon.torpedo',family:'torpedo',name:'Torpedo Tube',icon:'◆',color:'#ff735d',damage:155,rate:.24,range:1200,cost:2800,minHull:4,desc:'Fires a slow hunter-killer warhead with catastrophic impact.',homing:true,aoe:105,slow:true,kind:'heavy'},
    {id:'weapon.flak',family:'flak',name:'Flak Battery',icon:'✹',color:'#ffe39b',damage:14,rate:2.2,range:390,cost:1100,minHull:2,desc:'Fills nearby space with fragments and shreds swarms.',aoe:32,scatter:5,pointDefense:true,kind:'flak'}
  ];

  const ACTIVE_DATA=[
    ['Ion Bomb','⚡',18,'Disables nearby electronics and strips enemy shields.'],['Energy Nova','✹',20,'Blasts every nearby enemy with a radial energy shockwave.'],['Gravity Well','◎',24,'Drags enemies together and slows them for follow-up fire.'],['Blink Drive','◌',23,'Phases the flagship out of danger for a brief moment.'],['Shield Burst','⬡',22,'Restores a large chunk of shield and grants brief protection.'],['Reactor Vent','♨',25,'Dumps reactor heat outward as a damaging pulse.'],['Missile Barrage','⌁',28,'Launches a sudden swarm of homing missiles.'],['EMP','⌁',26,'Shuts down enemy shields and systems for a short window.'],['Drone Overdrive','◇',27,'Temporarily pushes all drones beyond normal limits.'],['Escort Assault','▷',29,'Orders escort craft into an aggressive strike pattern.'],['Emergency Repair','✚',31,'Repairs a large portion of damaged hull.'],['Target Lock','⊙',24,'Focuses targeting systems for a burst of lethal accuracy.'],['Mine Cloud','✣',30,'Seeds the battlespace with explosive proximity mines.'],['Decoy Beacon','◇',28,'Distracts hostile targeting away from the flagship.'],['Broadside','≋',25,'Instantly cycles all eligible weapon batteries.'],['Reactor Overcharge','⚡',32,'Temporarily boosts ship output at dangerous reactor load.'],['Singularity','●',38,'Compresses nearby enemies into a violent gravity event.'],['Artillery Strike','✦',36,'Calls a heavy delayed strike across the battlespace.']
  ];
  R.ACTIVES=ACTIVE_DATA.map((x,i)=>({id:'active.'+i,name:x[0],icon:x[1],cooldown:x[2],desc:x[3],cost:i<4?0:700+i*130,type:i}));

  R.PROFS=[['Pilot','Helm',0,'Improves flagship handling and targeting response.'],['Gunner','Fire Control',0,'Each assigned Gunner crews one additional weapon hardpoint.'],['Engineer','Engineering',1,'Keeps ship systems efficient and damage under control.'],['Reactor Tech','Reactor',1,'Improves reactor output for advanced systems.'],['Shield Specialist','Shield Console',1,'Improves shield recovery and resilience.'],['Drone Operator','Drone Control',1,'Required to fully operate drone bays.'],['Flight Officer','Hangar',3,'Required for escort craft and hangar operations.'],['Tactical Officer','Combat Info',2,'Improves threat response and priority targeting.'],['EW Officer','Sensors',2,'Improves disruption and electronic warfare systems.'],['Damage Control','Repair',2,'Improves hull recovery and emergency repairs.'],['Quartermaster','Logistics',2,'Improves salvage recovery and supply efficiency.'],['Executive Officer','Bridge',4,'Coordinates larger crews and fleet operations.']].map((x,i)=>({id:i,name:x[0],req:x[1],min:x[2],desc:x[3]}));

  R.FACTIONS=[['Swarm','#ff596d'],['Bastion','#d8b367'],['Vector','#59d8ff'],['Marauders','#ff8859'],['Null','#9584ff'],['Forge','#d78c56']].map((x,i)=>({id:i,name:x[0],color:x[1]}));
  R.ROLES=['Scout','Fighter','Interceptor','Bomber','Missile Boat','Support','Gunship','Carrier'];
  R.ENEMIES=[];R.FACTIONS.forEach(f=>R.ROLES.forEach((n,i)=>R.ENEMIES.push({id:`e.${f.id}.${i}`,faction:f.id,role:i,name:`${f.name} ${n}`,hp:.7+i*.32+(f.id===1?.25:0),speed:1.45-i*.11+(f.id===0?.35:0),damage:.7+i*.16,color:f.color,shield:f.id===2?.55:f.id===4?.2:0})));
  R.BOSSES=[];R.FACTIONS.forEach(f=>['Dreadnought','Carrier Prime','Reaper'].forEach((n,i)=>R.BOSSES.push({id:`b.${f.id}.${i}`,faction:f.id,name:`${f.name} ${n}`,hp:18+i*7,damage:2.3+i*.45,color:f.color,role:i})));

  R.RESEARCH_TRACKS=['Hull Integrity','Shield Grid','Reactor','Salvage','Targeting','Run Control'];R.RESEARCH=[];R.RESEARCH_TRACKS.forEach((t,ti)=>{for(let r=1;r<=6;r++)R.RESEARCH.push({id:`r.${ti}.${r}`,track:ti,rank:r,name:`${t} ${r}`,cost:220*r*r*(1+ti*.08),cores:r>=4?r-3:0});});

  const rarity=t=>['common','rare','epic'][t]||'common';R.CARDS=[];const add=o=>R.CARDS.push(o);
  const statCards=[['Damage','✦','damage',[.12,.20,.32],v=>`All weapons deal ${Math.round(v*100)}% more damage.`],['Fire Rate','»','rate',[.12,.20,.30],v=>`All weapons cycle ${Math.round(v*100)}% faster.`],['Critical','◆','crit',[.05,.08,.12],v=>`Critical hit chance increases by ${Math.round(v*100)}%.`],['Shield','⬡','shield',[.14,.23,.36],v=>`Maximum shield capacity increases by ${Math.round(v*100)}%.`],['Hull','♥','hull',[.14,.23,.36],v=>`Maximum hull strength increases by ${Math.round(v*100)}%.`],['Repair','✚','regen',[.25,.45,.75],v=>`The flagship repairs ${v.toFixed(2)} hull per second.`],['Cooldown','◔','cool',[.08,.13,.20],v=>`Active systems recharge ${Math.round(v*100)}% faster.`],['Extra Shot','•','shots',[1,1,2],v=>`Weapons fire ${v} additional projectile${v>1?'s':''} each cycle.`],['Blast Radius','✹','aoe',[.16,.28,.45],v=>`Explosive effects grow ${Math.round(v*100)}% larger.`],['Piercing','→','pierce',[1,2,3],v=>`Projectiles can pass through ${v} additional target${v>1?'s':''}.`],['Salvage','◇','salvage',[.20,.35,.55],v=>`Recovered salvage is worth ${Math.round(v*100)}% more.`],['Experience','△','xp',[.14,.24,.38],v=>`Combat experience is gained ${Math.round(v*100)}% faster.`]];
  for(let tier=0;tier<3;tier++)for(const s of statCards){const v=s[3][tier];add({id:`g.${s[2]}.${tier}`,group:'general',name:s[0]+(tier?` ${tier+1}`:''),icon:s[1],rarity:rarity(tier),desc:s[4](v),effect:{k:s[2],v}})}
  R.WEAPONS.forEach(w=>{const options=[['Tuning','common','damage',.18,`Your ${w.name} deals 18% more damage.`],['Cycle','rare','rate',.22,`Your ${w.name} cycles 22% faster.`],['Payload','rare',w.aoe?'aoe':'damage',w.aoe?.28:.24,w.aoe?`Your ${w.name} explosions are 28% larger.`:`Your ${w.name} deals 24% more damage.`],['Overdrive','epic','weaponSpecial',1,`Your ${w.name} gains an upgraded version of its signature behavior.`]];options.forEach((o,i)=>add({id:`w.${w.family}.${i}`,group:'weapon',family:w.family,name:`${w.name} ${o[0]}`,icon:w.icon,rarity:o[1],desc:o[4],effect:{k:o[2],v:o[3],family:w.family}}))});
  const defense=[['Barrier','⬡','shield',.16,'Increases maximum shield capacity by 16%.'],['Recharge','◔','shieldRegen',.25,'Shields regenerate 25% faster between impacts.'],['Plating','▰','armor',.04,'Reduces incoming hull damage with reinforced plating.'],['Nanites','✚','regen',.35,'Repair nanites slowly restore damaged hull.'],['Point Defense','✺','pd',.14,'Point defense has a better chance to erase hostile shots.'],['Emergency','♥','lowhp',.15,'Systems become stronger while hull integrity is critical.']];for(let tier=0;tier<3;tier++)defense.forEach((d,i)=>{const mult=1+tier*.6;add({id:`d.${i}.${tier}`,group:'defense',name:d[0]+(tier?` ${tier+1}`:''),icon:d[1],rarity:rarity(tier),desc:d[4],effect:{k:d[2],v:d[3]*mult}})});
  const support=[['Drone Damage','◇','droneDmg',.20,'Drones deal 20% more damage.','drone'],['Drone Rate','◇','droneRate',.20,'Drones attack 20% faster.','drone'],['Drone Count','◇','drones',1,'Deploy one additional combat drone.','drone'],['Escort Damage','▷','escortDmg',.20,'Escort craft deal 20% more damage.','escort'],['Escort Rate','▷','escortRate',.20,'Escort craft attack 20% faster.','escort'],['Escort Wing','▷','escorts',1,'Deploy one additional escort craft.','escort']];for(let tier=0;tier<3;tier++)support.forEach((s,i)=>add({id:`s.${i}.${tier}`,group:'support',requires:s[5],name:s[0]+(tier?` ${tier+1}`:''),icon:s[1],rarity:rarity(tier),desc:s[4],effect:{k:s[2],v:(s[2]==='drones'||s[2]==='escorts')?1:s[3]*(1+tier*.55)}}));
  const activeTags=[['Ion Systems','⚡','ion','Ion-based active systems recharge faster.'],['Nova Systems','✹','nova','Energy burst systems recharge faster.'],['Gravity Systems','◎','gravity','Gravity-based active systems recharge faster.'],['Shield Systems','⬡','shieldActive','Shield active systems recharge faster.'],['Repair Systems','✚','repairActive','Repair active systems recharge faster.'],['Missile Systems','⌁','missileActive','Missile active systems recharge faster.']];for(let tier=0;tier<3;tier++)activeTags.forEach((a,i)=>add({id:`a.${i}.${tier}`,group:'active',name:a[0]+(tier?` ${tier+1}`:''),icon:a[1],rarity:rarity(tier),desc:a[3],effect:{k:'active',v:.10+tier*.07}}));
  [['Stormhead','⚡','Ion weapons make missile impacts arc electricity into nearby ships.',['ion','missile']],['Hard Reboot','⬡','Breaking your shield releases a defensive energy pulse.',['shield']],['Plasma Net','♨','Plasma explosions leave a short-lived burning field.',['plasma']],['Thunder Rail','→','Railgun hits discharge ion energy into nearby targets.',['railgun','ion']],['Hive Mind','◇','Drone kills briefly accelerate the rest of the drone wing.',['drone']],['Wolfpack','▷','Escort craft focus the same target for escalating damage.',['escort']],['Chain Reaction','✹','Explosions can trigger smaller secondary explosions.',['plasma','missile']],['Blackout','⚡','Ion effects briefly suppress enemy weapons after shields collapse.',['ion']],['Flak Wall','✹','Flak also destroys nearby hostile projectiles.',['flak']],['Deadeye','◆','Critical hits mark enemies for increased follow-up damage.',['railgun']],['Gravity Bombs','◎','Explosions pull nearby enemies toward their center.',['plasma','missile']],['Carrier Doctrine','▷','Drones and escorts gain damage while both are deployed.',['drone','escort']]].forEach((x,i)=>add({id:'y'+i,group:'synergy',name:x[0],icon:x[1],rarity:'epic',desc:x[2],requiresAny:x[3],effect:{k:'synergy',v:i}}));
  [['Bullet Time','◔','Enemy projectiles slow while your weapons continue firing at full speed.'],['Event Horizon','◎','Explosions pull enemies inward before detonating.'],['Storm Crown','⚡','Ion effects chain farther and hit dramatically harder.'],['Living Hull','♥','Hull regeneration accelerates as damage becomes more severe.'],['Missile God','⌁','Missiles split into additional warheads before impact.'],['Fleet Command','▷','All allied drones and escorts gain a major global boost.'],['Redline','♨','Weapon fire rate surges at the cost of weaker defenses.'],['Second Heart','♥','Survive one fatal hit and restore part of the flagship hull.']].forEach((x,i)=>add({id:'l'+i,group:'legendary',name:x[0],icon:x[1],rarity:'legendary',desc:x[2],effect:{k:'legendary',v:i}}));
  [['Doomsday','☠','Damage rises massively, but maximum hull is permanently reduced this run.'],['Unstable Core','☠','Systems recharge much faster, but shield capacity is reduced.'],['Blood Shield','☠','Hull damage fuels shield restoration, but repairs are weaker.'],['Zero Margin','☠','Critical damage explodes upward while survivability collapses.']].forEach((x,i)=>add({id:'c'+i,group:'cursed',name:x[0],icon:x[1],rarity:'cursed',desc:x[2],effect:{k:'cursed',v:i}}));

  const N1=['Aria','Kade','Mira','Talon','Rhea','Jax','Nova','Soren','Lyra','Cato','Vera','Orin'],N2=['Vale','Rook','Sol','Voss','Rey','Dane','Kael','Morrow'];R.crew=()=>({id:Date.now()+Math.random(),name:pick(N1)+' '+pick(N2),profession:Math.random()*12|0,level:1,xp:0,skill:+(Math.random()*.22+.9).toFixed(2),assigned:false});
  const KEY='sr_mobile_v2';R.loadAll=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{slots:{},last:1}}catch{return{slots:{},last:1}}};R.save=s=>{let a=R.loadAll();a.slots[s.slot]=s;a.last=s.slot;localStorage.setItem(KEY,JSON.stringify(a));};
  R.migrate=s=>{if(!s)return s;s.quarters=Math.max(2,Math.min(R.HULLS[s.hull||0].crew,s.quarters||s.crew?.filter(x=>x.assigned).length||2));s.research=s.research||{};s.packs=s.packs||[];s.settings=s.settings||{audio:1,haptics:true};const familyFrom=id=>{const m=/weapon\.([^.]+)/.exec(id||'');return m?.[1]},mapFamily=f=>R.WEAPONS.find(w=>w.family===f)?.id,converted=(s.weapons||[]).map(x=>R.WEAPONS.some(w=>w.id===x)?x:mapFamily(familyFrom(x))).filter(Boolean);s.weapons=[...new Set(converted.length?converted:['weapon.autocannon','weapon.pulse'])].slice(0,R.HULLS[s.hull||0].weapons);const unlocked=(s.unlockedW||[]).map(x=>R.WEAPONS.some(w=>w.id===x)?x:mapFamily(familyFrom(x))).filter(Boolean);s.unlockedW=[...new Set([...unlocked,'weapon.autocannon','weapon.pulse'])];s.unlockedA=s.unlockedA||['active.0','active.1','active.3','active.4'];return s};R.getSlot=n=>{const s=R.loadAll().slots[n]||null;if(s){R.migrate(s);R.save(s)}return s};
  R.newSave=n=>{let c1=R.crew(),c2=R.crew();c1.profession=0;c2.profession=1;c1.assigned=c2.assigned=true;let s={slot:n,salvage:700,cores:0,hull:0,quarters:2,weapons:['weapon.autocannon','weapon.pulse'],actives:['active.0'],unlockedW:['weapon.autocannon','weapon.pulse'],unlockedA:['active.0','active.1','active.3','active.4'],crew:[c1,c2],research:{},records:{wave:0,kills:0,runs:0,bosses:0},packs:[],settings:{audio:1,haptics:true}};R.save(s);return s};
  R.audio={ctx:null,master:1,play(type,pan=0){try{this.ctx=this.ctx||new (AudioContext||webkitAudioContext)();const c=this.ctx,t=c.currentTime,o=c.createOscillator(),g=c.createGain(),p=c.createStereoPanner?c.createStereoPanner():null,M={shot:[210,.055,'square',.032,95],laser:[720,.07,'sawtooth',.022,420],rail:[90,.13,'square',.06,45],missile:[145,.09,'sawtooth',.035,80],ion:[560,.10,'triangle',.035,180],hit:[105,.08,'square',.055,55],shield:[430,.10,'sine',.05,260],shieldBreak:[180,.22,'sawtooth',.08,70],boom:[62,.22,'sawtooth',.085,28],asteroid:[120,.09,'triangle',.04,80],ui:[520,.035,'sine',.025,430],deny:[170,.08,'square',.03,120],boss:[72,.35,'sawtooth',.1,38],level:[700,.14,'sine',.05,980],cash:[830,.055,'sine',.035,1040]},m=M[type]||M.ui;o.type=m[2];o.frequency.setValueAtTime(m[0],t);o.frequency.exponentialRampToValueAtTime(Math.max(20,m[4]),t+m[1]);g.gain.setValueAtTime(m[3]*(this.master||1),t);g.gain.exponentialRampToValueAtTime(.0001,t+m[1]);o.connect(g);if(p){p.pan.value=clamp(pan,-1,1);g.connect(p);p.connect(c.destination)}else g.connect(c.destination);o.start();o.stop(t+m[1])}catch{}}};
})();