(()=>{
const R=window.SR,$=s=>document.querySelector(s),E=(t,c,h)=>{let e=document.createElement(t);if(c)e.className=c;if(h!=null)e.innerHTML=h;return e},B=(h,f,c='btn')=>{let b=E('button',c,h);b.onclick=()=>{R.audio.play('ui');f()};return b},fmt=n=>n<1000?Math.floor(n):n<1e6?(n/1000).toFixed(1)+'k':(n/1e6).toFixed(1)+'m';
class App{
constructor(){this.s=null;this.tab='ship';this.arsenalMode='w';this.fleetMode='d';this.main()}
shell(title='LOE: STARSHIP SURVIVOR'){document.body.className='';let a=$('#app');a.innerHTML='';let h=E('header','top',`<b>${title}</b><span id="cash"></span>`),m=E('main','screen');a.append(h,m);return m}
cash(){let c=$('#cash');if(c&&this.s)c.innerHTML=`▰ ${fmt(this.s.salvage)} &nbsp; ◆ ${this.s.cores}`}
main(){this.s=null;let m=this.shell();m.className='screen center';m.innerHTML='<div class="logo"><span>◆</span><small>LEGENDS OF EDEN</small><b>STARSHIP<br>SURVIVOR</b><em>v'+R.VERSION+'</em></div>';let x=E('div','menu'),a=R.loadAll(),last=R.getSlot(a.last);if(last)x.append(B('▶ CONTINUE',()=>{this.s=last;R.audio.master=this.s.settings?.audio??1;this.station()},'btn primary'));x.append(B('NEW / LOAD',()=>this.slots()));x.append(B('⚙ SETTINGS',()=>this.settings(),'btn quiet'));m.append(x)}
slots(){let m=this.shell('SAVE SLOTS');for(let i=1;i<=3;i++){let s=R.getSlot(i),p=E('div','panel save',s?`<b>SLOT ${i}</b><span>◈ ${s.records.wave} · ${R.HULLS[s.hull].name}</span>`:`<b>SLOT ${i}</b><span>EMPTY</span>`);p.onclick=()=>{this.s=s||R.newSave(i);R.audio.master=this.s.settings?.audio??1;this.station()};m.append(p)}m.append(B('‹ BACK',()=>this.main(),'btn back'))}
settings(){let a=R.loadAll(),slot=R.getSlot(a.last);this.s=slot;let m=this.shell('SETTINGS');if(this.s)this.cash();m.append(E('div','sectionTitle','AUDIO'));let current=this.s?.settings?.audio??R.audio.master??1,aud=E('div','panel row',`<span><b>♪ MASTER AUDIO</b><small>${Math.round(current*100)}%</small></span>`),range=E('input','range');range.type='range';range.min=0;range.max=1;range.step=.1;range.value=current;range.oninput=()=>{R.audio.master=+range.value;aud.querySelector('small').textContent=Math.round(+range.value*100)+'%';if(this.s){this.s.settings=this.s.settings||{};this.s.settings.audio=+range.value;R.save(this.s)}};aud.append(range);m.append(aud,B('♪ TEST SOUND',()=>R.audio.play('level'),'btn small'));m.append(E('div','sectionTitle','EMBERPACKS'));if(!this.s){m.append(E('div','panel','<b>NO ACTIVE SAVE</b><small>Create a save before importing Emberpacks.</small>'))}else{m.append(E('div','hint','<span>◇ MODULAR CONTENT</span><small>Import declarative packs here. They stay outside the station flow.</small>'));let inp=E('input');inp.type='file';inp.accept='.json,.emberpack';inp.onchange=async()=>{try{let j=JSON.parse(await inp.files[0].text());this.s.packs.push(j);if(j.theme)for(let[k,v]of Object.entries(j.theme))document.documentElement.style.setProperty('--'+k,v);R.save(this.s);this.toast('PACK LOADED');this.settings()}catch{this.deny('INVALID PACK')}};m.append(inp);this.s.packs.forEach(p=>m.append(E('div','panel row',`<span><b>${p.name||p.id||'PACK'}</b><small>${p.version||''}</small></span><i class="ok">✓</i>`)))}if(this.s){m.append(E('div','sectionTitle','SAVE'));m.append(B('RESET CURRENT SAVE',()=>{if(confirm('Reset this save slot?')){let all=R.loadAll();delete all.slots[this.s.slot];localStorage.setItem('sr_mobile_v2',JSON.stringify(all));this.s=null;this.main()}},'btn danger'))}m.append(B('‹ MAIN MENU',()=>this.main(),'btn back'))}
station(t=this.tab){this.tab=t;let m=this.shell('STATION');this.cash();let nav=E('nav','nav');[['ship','🚀','SHIP'],['systems','△','SYSTEMS'],['arsenal','⊙','ARSENAL'],['crew','👥','CREW'],['fleet','◇','FLEET'],['research','◆','RESEARCH']].forEach(x=>{let b=B(`<i>${x[1]}</i><small>${x[2]}</small>`,()=>this.station(x[0]),'nbtn '+(t===x[0]?'on':''));nav.append(b)});m.append(nav);let c=E('section','content');m.append(c);this['tab_'+t](c);let foot=E('footer','foot');foot.append(B('≡',()=>this.main(),'btn small'),B('▶ LAUNCH',()=>this.launch(),'btn primary launch'));m.append(foot)}
assigned(prof){return this.s.crew.filter(x=>x.assigned&&x.profession===prof).length}
weaponCapacity(){return Math.min(R.HULLS[this.s.hull].weapons,1+this.assigned(1))}
droneCapacity(){let h=R.HULLS[this.s.hull];return this.assigned(5)>0?Math.min(h.droneCap,this.s.systems.droneBay||0):0}
flightCrew(){return Math.max(0,this.assigned(0)-1)+this.assigned(6)}
supportCrewUsed(){return this.s.equippedSupports.reduce((n,id)=>n+(R.SUPPORTS.find(x=>x.id===id)?.crewReq||0),0)}
supportCapacity(){return Math.min(R.HULLS[this.s.hull].supportCap,this.s.systems.hangar||0)}
displayHp(){return Math.round(R.HULLS[this.s.hull].hp*(1+(this.s.research[0]||0)*.04))}
displayShield(){return Math.round(R.HULLS[this.s.hull].shield*(1+(this.s.research[1]||0)*.04)*(1+(this.s.systems.shield||0)*.10))}
infoBtn(title,desc,current,next,curVal=0,nextVal=0,maxVal=1){let b=B('ⓘ',()=>this.info(title,desc,current,next,curVal,nextVal,maxVal),'ibtn');b.setAttribute('aria-label','Info');return b}
info(title,desc,current,next,curVal=0,nextVal=0,maxVal=1){let old=$('#sheet');if(old)old.remove();let sh=E('div','sheet');sh.id='sheet';sh.innerHTML=`<div class="sheetCard"><button class="sheetClose">×</button><small>SHIP DATA</small><h2>${title}</h2><p>${desc}</p><div class="compare"><span>CURRENT<b>${current}</b></span><span>${next?'NEXT':'STATUS'}<b>${next||'MAXIMUM'}</b></span></div><div class="meter"><i style="width:${Math.min(100,curVal/maxVal*100)}%"></i><em style="left:${Math.min(100,nextVal/maxVal*100)}%"></em></div></div>`;document.body.append(sh);sh.onclick=e=>{if(e.target===sh||e.target.classList.contains('sheetClose'))sh.remove()};R.audio.play('ui')}
tab_ship(c){let h=R.HULLS[this.s.hull],p=E('div','shipHero');p.innerHTML=`<canvas id="ship" width="520" height="300"></canvas><small>FLAGSHIP</small><h1>${h.name}</h1>`;c.append(p);setTimeout(()=>this.drawShipPreview(),0);let sg=E('div','statGrid');[['♥','HULL',this.displayHp()],['⬡','SHIELD',this.displayShield()],['⊙','WEAPONS',`${this.s.weapons.length}/${this.weaponCapacity()}`],['👥','CREW',`${this.s.crew.filter(x=>x.assigned).length}/${this.s.quarters}`],['◇','DRONES',`${this.s.equippedDrones.length}/${this.droneCapacity()}`],['▷','SUPPORT',`${this.s.equippedSupports.length}/${this.supportCapacity()}`]].forEach(x=>sg.append(E('div','statCell',`<i>${x[0]}</i><small>${x[1]}</small><b>${x[2]}</b>`)));c.append(sg);c.append(E('div','sectionTitle','RECORD'));let rg=E('div','recordGrid');[['◈','HIGHEST WAVE',this.s.records.wave],['✕','SHIPS DESTROYED',fmt(this.s.records.kills)],['◆','BOSSES DESTROYED',this.s.records.bosses],['↻','RUNS',this.s.records.runs]].forEach(x=>rg.append(E('div','recordCell',`<i>${x[0]}</i><small>${x[1]}</small><strong>${x[2]}</strong>`)));c.append(rg)}
drawShipPreview(){let cv=$('#ship');if(!cv)return;let x=cv.getContext('2d'),w=cv.width,h=cv.height,t=this.s.hull;x.clearRect(0,0,w,h);for(let i=0;i<80;i++){x.fillStyle='rgba(255,255,255,.25)';x.fillRect(Math.random()*w,Math.random()*h,1,1)}R.drawShip?.(x,w/2,h/2,1+t*.11,this.s.weapons,t,true,{drones:this.s.equippedDrones,supports:this.s.equippedSupports})}
tab_systems(c){let h=R.HULLS[this.s.hull];c.append(E('div','hint','<span>△ SHIP SYSTEMS</span><small>Permanent structure lives here. Locks show the next physical dependency.</small>'));this.hullUpgrade(c);this.quartersUpgrade(c);['shield','armor','reactor','engines','droneBay','hangar'].forEach(k=>this.systemUpgrade(c,k,h))}
hullUpgrade(c){let h=R.HULLS[this.s.hull],r=E('div','panel upgrade');let next=R.HULLS[this.s.hull+1];r.append(E('span','upIcon','△'),E('div','upBody',`<b>HULL FRAME</b><small>${h.name}</small>`));let cur=`${h.weapons} hardpoints · ${h.crew} max crew`,nxt=next?`${next.weapons} hardpoints · ${next.crew} max crew`:null;r.append(this.infoBtn('Hull Frame','The hull sets the physical ceiling for hardpoints, crew, drones, hangars, hull strength, and active systems.',cur,nxt,this.s.hull,next?this.s.hull+1:this.s.hull,6));if(next){let core=Math.max(0,next.tier-1);r.append(B(`△ ${next.name}<small>▰ ${fmt(next.cost)}${core?' · ◆ '+core:''}</small>`,()=>{if(this.s.salvage<next.cost||this.s.cores<core)return this.deny('NEED RESOURCES');this.s.salvage-=next.cost;this.s.cores-=core;this.s.hull++;R.save(this.s);this.station('systems')},'btn upgradeBtn'))}else r.append(E('i','ok','✓'));c.append(r)}
quartersUpgrade(c){let h=R.HULLS[this.s.hull],q=this.s.quarters,max=h.crew,cost=250+q*220,r=E('div','panel upgrade');r.append(E('span','upIcon','👥'),E('div','upBody',`<b>CREW QUARTERS</b><small>${q}/${max} bunks installed</small>`));r.append(this.infoBtn('Crew Quarters','Bunks determine how many crew can live aboard and be assigned to ship systems.',`${q} bunks`,q<max?`${q+1} bunks`:'',q,q<max?q+1:q,max));if(q<max)r.append(B(`+1 BUNK<small>▰ ${fmt(cost)}</small>`,()=>{if(this.s.salvage<cost)return this.deny('NEED SALVAGE');this.s.salvage-=cost;this.s.quarters++;R.save(this.s);this.station('systems')},'btn upgradeBtn'));else if(this.s.hull<6)r.append(E('em','lock','🔒 LARGER HULL'));else r.append(E('i','ok','✓'));c.append(r)}
systemUpgrade(c,key,h){let s=R.SYSTEMS[key],lvl=this.s.systems[key]||0,minHull=key==='droneBay'?1:key==='hangar'?3:0,hullCap=key==='droneBay'?h.droneCap:key==='hangar'?h.supportCap:Math.min(s.max,2+this.s.hull),max=Math.min(s.max,hullCap),r=E('div','panel upgrade '+(this.s.hull<minHull?'locked':''));r.append(E('span','upIcon',s.icon),E('div','upBody',`<b>${s.name}</b><small>${s.stat(lvl)}</small>`));r.append(this.infoBtn(s.name,s.desc,s.stat(lvl),lvl<max?s.stat(lvl+1):'',lvl,lvl<max?lvl+1:lvl,s.max));if(this.s.hull<minHull)r.append(E('em','lock',`🔒 ${R.HULLS[minHull].name}`));else if(lvl<max){let cost=s.cost(lvl);r.append(B(`LV ${lvl+1}<small>▰ ${fmt(cost)}</small>`,()=>{if(this.s.salvage<cost)return this.deny('NEED SALVAGE');this.s.salvage-=cost;this.s.systems[key]=lvl+1;R.save(this.s);this.station('systems')},'btn upgradeBtn'))}else if(max<s.max)r.append(E('em','lock','🔒 LARGER HULL'));else r.append(E('i','ok','✓'));c.append(r)}
tab_arsenal(c){let head=E('div','tabs');head.append(B('⊙ WEAPONS',()=>{this.arsenalMode='w';this.station('arsenal')},'btn small '+(this.arsenalMode==='w'?'primary':'')),B('⚡ ACTIVES',()=>{this.arsenalMode='a';this.station('arsenal')},'btn small '+(this.arsenalMode==='a'?'primary':'')));c.append(head);this.arsenalMode==='w'?this.listWeapons(c):this.listActives(c)}
listWeapons(c){let h=R.HULLS[this.s.hull];c.append(E('div','hint',`<span>⊙ ${this.s.weapons.length}/${this.weaponCapacity()}</span><small>Hull supplies hardpoints. Every extra mounted weapon needs another assigned Gunner.</small>`));R.WEAPONS.forEach(w=>{let owned=this.s.unlockedW.includes(w.id),on=this.s.weapons.includes(w.id),hullOK=this.s.hull>=w.minHull,r=E('div','panel gear '+(on?'on ':'')+(!hullOK?'locked':''));r.append(E('i','gearIcon',w.icon),E('span','gearBody',`<b>${w.name}</b><small>${w.desc}</small>${!hullOK?`<em>🔒 ${R.HULLS[w.minHull].name}</em>`:''}`),this.infoBtn(w.name,w.desc,`${Math.round(w.damage)} dmg · ${w.rate.toFixed(1)}/s`,owned?(on?'MOUNTED':'OWNED'):`▰ ${fmt(w.cost)}`,Math.min(1,w.damage/170),Math.min(1,w.damage/170),1));let b;if(!hullOK)b=E('button','btn small ghost','LOCKED');else if(!owned)b=B(`BUY<small>▰ ${fmt(w.cost)}</small>`,()=>{if(this.s.salvage<w.cost)return this.deny('NEED SALVAGE');this.s.salvage-=w.cost;this.s.unlockedW.push(w.id);R.save(this.s);this.station('arsenal')},'btn small');else b=B(on?'REMOVE':'EQUIP',()=>{if(on)this.s.weapons=this.s.weapons.filter(x=>x!==w.id);else if(this.s.weapons.length>=h.weapons)return this.deny('NEED HULL HARDPOINT');else if(this.s.weapons.length>=this.weaponCapacity())return this.deny('NEED ANOTHER GUNNER');else this.s.weapons.push(w.id);R.save(this.s);this.station('arsenal')},'btn small');r.append(b);c.append(r)})}
listActives(c){let h=R.HULLS[this.s.hull];c.append(E('div','hint',`<span>⚡ ${this.s.actives.length}/${h.active}</span><small>Active-system slots come from the hull frame.</small>`));R.ACTIVES.forEach(a=>{let owned=this.s.unlockedA.includes(a.id),on=this.s.actives.includes(a.id),r=E('div','panel gear '+(on?'on':''));r.append(E('i','gearIcon',a.icon),E('span','gearBody',`<b>${a.name}</b><small>${a.desc}</small>`),this.infoBtn(a.name,a.desc,`${a.cooldown}s cooldown`,owned?(on?'EQUIPPED':'OWNED'):`▰ ${fmt(a.cost)}`,0,0,1));r.append(B(!owned?`BUY<small>▰ ${fmt(a.cost)}</small>`:on?'REMOVE':'EQUIP',()=>{if(!owned){if(this.s.salvage<a.cost)return this.deny('NEED SALVAGE');this.s.salvage-=a.cost;this.s.unlockedA.push(a.id)}else if(on)this.s.actives=this.s.actives.filter(x=>x!==a.id);else if(this.s.actives.length<h.active)this.s.actives.push(a.id);else return this.deny('NEED LARGER HULL');R.save(this.s);this.station('arsenal')},'btn small'));c.append(r)})}
tab_crew(c){let assigned=this.s.crew.filter(x=>x.assigned).length;c.append(E('div','hint',`<span>👥 ${assigned}/${this.s.quarters}</span><small>${this.s.crew.length} aboard · quarters limit total crew, while professions unlock ship capabilities.</small>`));this.s.crew.forEach(cr=>{let p=R.PROFS[cr.profession],ok=this.s.hull>=p.min,r=E('div','panel crew '+(cr.assigned?'on ':'')+(!ok?'locked':''));r.append(E('i','gearIcon','★'),E('span','gearBody',`<b>${cr.name}</b><small>${p.name} · Lv ${cr.level}</small><small>${p.desc}</small>${!ok?`<em>🔒 ${R.HULLS[p.min].name}</em>`:''}`),this.infoBtn(p.name,p.desc,`Lv ${cr.level} · skill ${cr.skill}`,cr.assigned?'ASSIGNED':'AVAILABLE',cr.skill,cr.skill,1.2));r.append(B(cr.assigned?'OFF':'ASSIGN',()=>{if(!ok)return this.deny('SHIP TOO SMALL');if(!cr.assigned&&this.s.crew.filter(x=>x.assigned).length>=this.s.quarters)return this.deny('QUARTERS FULL');cr.assigned=!cr.assigned;R.save(this.s);this.station('crew')},'btn small'));c.append(r)});const full=this.s.crew.length>=this.s.quarters;let hire=R.crew(),p=R.PROFS[hire.profession],cost=300;if(full)c.append(E('div','panel row locked','<span><b>+ RECRUIT</b><small>🔒 INCREASE CREW QUARTERS</small></span>'));else c.append(B(`+ RECRUIT ${p.name}<small>▰ ${cost}</small>`,()=>{if(this.s.salvage<cost)return this.deny('NEED SALVAGE');this.s.salvage-=cost;this.s.crew.push(hire);R.save(this.s);this.station('crew')},'btn primary recruit'))}
tab_fleet(c){let head=E('div','tabs');head.append(B('◇ DRONES',()=>{this.fleetMode='d';this.station('fleet')},'btn small '+(this.fleetMode==='d'?'primary':'')),B('▷ SUPPORT',()=>{this.fleetMode='s';this.station('fleet')},'btn small '+(this.fleetMode==='s'?'primary':'')));c.append(head);this.fleetMode==='d'?this.listDrones(c):this.listSupports(c)}
listDrones(c){let cap=this.droneCapacity(),op=this.assigned(5)>0;c.append(E('div','hint',`<span>◇ ${this.s.equippedDrones.length}/${cap}</span><small>${op?'Drone Operator online.':'🔒 Assign a Drone Operator.'} Upgrade the Drone Bay in Systems for capacity.</small>`));c.append(E('div','fleetLegend','<span>OFFENSE · roam within a leash</span><span>DEFENSE · orbit the flagship</span>'));R.DRONES.forEach(d=>{let owned=this.s.ownedDrones.includes(d.id),on=this.s.equippedDrones.includes(d.id),hullOK=this.s.hull>=d.minHull,r=E('div','panel gear '+(on?'on ':'')+(!hullOK?'locked':''));r.append(E('i','gearIcon',d.icon),E('span','gearBody',`<b>${d.name}</b><small><strong>${d.role.toUpperCase()}</strong> · ${d.desc}</small>${!hullOK?`<em>🔒 ${R.HULLS[d.minHull].name}</em>`:''}`),this.infoBtn(d.name,d.desc,d.role.toUpperCase(),owned?(on?'DEPLOYED':'OWNED'):`▰ ${fmt(d.cost)}`,0,0,1));r.append(B(!owned?`BUY<small>▰ ${fmt(d.cost)}</small>`:on?'REMOVE':'EQUIP',()=>{if(!hullOK)return this.deny('NEED LARGER HULL');if(!owned){if(this.s.salvage<d.cost)return this.deny('NEED SALVAGE');this.s.salvage-=d.cost;this.s.ownedDrones.push(d.id)}else if(on)this.s.equippedDrones=this.s.equippedDrones.filter(x=>x!==d.id);else{if(!op)return this.deny('NEED DRONE OPERATOR');if(this.s.equippedDrones.length>=cap)return this.deny(this.s.systems.droneBay?'DRONE BAY FULL':'NEED DRONE BAY');this.s.equippedDrones.push(d.id)}R.save(this.s);this.station('fleet')},'btn small'));c.append(r)})}
listSupports(c){let cap=this.supportCapacity(),crew=this.flightCrew(),used=this.supportCrewUsed();c.append(E('div','hint',`<span>▷ ${this.s.equippedSupports.length}/${cap}</span><small>${used}/${crew} flight crew committed · support ships begin at Corvette hulls and require hangars.</small>`));R.SUPPORTS.forEach(s=>{let owned=this.s.ownedSupports.includes(s.id),on=this.s.equippedSupports.includes(s.id),hullOK=this.s.hull>=s.minHull,r=E('div','panel gear '+(on?'on ':'')+(!hullOK?'locked':''));r.append(E('i','gearIcon',s.icon),E('span','gearBody',`<b>${s.name}</b><small>${s.crewReq} crew · ${s.desc}</small>${!hullOK?`<em>🔒 ${R.HULLS[s.minHull].name}</em>`:''}`),this.infoBtn(s.name,s.desc,`${s.crewReq} flight crew`,owned?(on?'DEPLOYED':'OWNED'):`▰ ${fmt(s.cost)}`,s.crewReq,s.crewReq,2));r.append(B(!owned?`BUY<small>▰ ${fmt(s.cost)}</small>`:on?'REMOVE':'EQUIP',()=>{if(!hullOK)return this.deny('NEED LARGER HULL');if(!owned){if(this.s.salvage<s.cost)return this.deny('NEED SALVAGE');this.s.salvage-=s.cost;this.s.ownedSupports.push(s.id)}else if(on)this.s.equippedSupports=this.s.equippedSupports.filter(x=>x!==s.id);else{if(!this.s.systems.hangar)return this.deny('NEED HANGAR');if(this.s.equippedSupports.length>=cap)return this.deny('HANGAR FULL');if(used+s.crewReq>crew)return this.deny(`NEED ${s.crewReq} FLIGHT CREW`);this.s.equippedSupports.push(s.id)}R.save(this.s);this.station('fleet')},'btn small'));c.append(r)})}
tab_research(c){c.append(E('div','hint','<span>◆ RESEARCH</span><small>Permanent refinements. Physical ship capacity still comes from Systems, crew, and equipment.</small>'));R.RESEARCH_TRACKS.forEach((t,i)=>{let rank=this.s.research[i]||0,n=R.RESEARCH.find(x=>x.track===i&&x.rank===rank+1),r=E('div','panel researchRow');r.append(E('span','researchBody',`<b>${t.name}</b><small>${'●'.repeat(rank)}${'○'.repeat(6-rank)}</small>`),this.infoBtn(t.name,t.desc,`${t.stat}: +${rank*t.step}${t.stat==='Hull'||t.stat==='Shield'||t.stat==='Cooldown'||t.stat==='Salvage'||t.stat==='Tracking'?'%':''}`,rank<6?`${t.stat}: +${(rank+1)*t.step}${t.stat==='Hull'||t.stat==='Shield'||t.stat==='Cooldown'||t.stat==='Salvage'||t.stat==='Tracking'?'%':''}`:'',rank,Math.min(6,rank+1),6));if(n)r.append(B(`LV ${n.rank}<small>▰ ${fmt(n.cost)}${n.cores?' · ◆ '+n.cores:''}</small>`,()=>{if(this.s.salvage<n.cost||this.s.cores<n.cores)return this.deny('NEED RESOURCES');this.s.salvage-=n.cost;this.s.cores-=n.cores;this.s.research[i]=rank+1;R.save(this.s);this.station('research')},'btn small'));else r.append(E('i','ok','✓'));c.append(r)})}
launch(){R.save(this.s);new R.Game(this,this.s)}
finish(summary){this.s.salvage+=summary.salvage;this.s.cores+=summary.cores;this.s.records.wave=Math.max(this.s.records.wave,summary.wave);this.s.records.kills+=summary.kills;this.s.records.runs++;this.s.records.bosses+=summary.bosses;R.save(this.s);let m=this.shell('RUN ENDED');this.cash();m.innerHTML=`<div class="panel report"><strong>◈ ${summary.wave}</strong><span>✕ ${fmt(summary.kills)} ships &nbsp; ◆ ${summary.bosses} bosses</span><span>▰ +${fmt(summary.salvage)} &nbsp; ◆ +${summary.cores}</span></div>`;m.append(B('STATION',()=>this.station(),'btn primary'),B('▶ AGAIN',()=>this.launch(),'btn'))}
toast(t){let x=$('#toast');if(!x){x=E('div','toast');x.id='toast';document.body.append(x)}x.textContent=t;x.classList.remove('deny');x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1400)}
deny(t){R.audio.play('deny');let x=$('#toast');if(!x){x=E('div','toast');x.id='toast';document.body.append(x)}x.textContent='🔒 '+t;x.classList.add('deny','show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1600)}
}
R.App=App;addEventListener('DOMContentLoaded',()=>R.app=new App());
})();
