(()=>{
'use strict';
const R=window.SR;if(!R?.App||!R?.Game)return;
R.VERSION='0.9.7';
const AP=R.App.prototype,GP=R.Game.prototype,$=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));

const migrate97=R.migrate;
R.migrate=s=>{s=migrate97(s);if(!s)return s;s.version='0.9.7';return s};

R.v97DrawFlagship=function(ctx,cx,cy,scale,save={},opt={}){
  const hull=clamp(save.hull|0,0,6),mounts=(save.weaponMounts||save.weapons||[]).filter(Boolean),drones=save.equippedDrones||save.drones||[],supports=save.equippedSupports||save.supports||[],targets=opt.weaponTargets||[],t=opt.t||0;
  const z=34*scale,accent=opt.accent||'#75ddf7',body=opt.body||'#b9c8d4',dark='#12232e';
  const shapes=[[[0,-1.18],[.43,-.32],[.68,.48],[.28,.82],[0,.61],[-.28,.82],[-.68,.48],[-.43,-.32]],[[0,-1.24],[.56,-.48],[.82,.42],[.48,.76],[.22,.68],[0,.88],[-.22,.68],[-.48,.76],[-.82,.42],[-.56,-.48]],[[0,-1.24],[.48,-.73],[.9,-.12],[.88,.56],[.45,.82],[.16,.66],[0,.94],[-.16,.66],[-.45,.82],[-.88,.56],[-.9,-.12],[-.48,-.73]],[[0,-1.42],[.45,-.88],[.94,-.28],[1,.42],[.62,.8],[.27,.7],[0,1.02],[-.27,.7],[-.62,.8],[-1,.42],[-.94,-.28],[-.45,-.88]],[[0,-1.52],[.42,-1.02],[.88,-.58],[1.08,.1],[.94,.64],[.48,.92],[.18,.77],[0,1.1],[-.18,.77],[-.48,.92],[-.94,.64],[-1.08,.1],[-.88,-.58],[-.42,-1.02]],[[0,-1.62],[.48,-1.16],[.98,-.68],[1.16,-.02],[1.02,.66],[.58,.96],[.24,.82],[0,1.17],[-.24,.82],[-.58,.96],[-1.02,.66],[-1.16,-.02],[-.98,-.68],[-.48,-1.16]],[[0,-1.72],[.55,-1.28],[1.05,-.8],[1.24,-.16],[1.18,.54],[.76,.93],[.34,.86],[0,1.24],[-.34,.86],[-.76,.93],[-1.18,.54],[-1.24,-.16],[-1.05,-.8],[-.55,-1.28]]];
  ctx.save();ctx.translate(cx,cy);const engines=hull<2?2:hull<5?3:4;
  for(let i=0;i<engines;i++){const off=(i-(engines-1)/2)*z*.25,flame=z*(.52+.11*Math.sin(t*5+i));ctx.globalAlpha=.16+.07*Math.sin(t*4+i);ctx.fillStyle=accent;ctx.beginPath();ctx.moveTo(off-z*.08,z*.7);ctx.lineTo(off,z*.7+flame);ctx.lineTo(off+z*.08,z*.7);ctx.fill()}ctx.globalAlpha=1;
  if(hull>=2){ctx.fillStyle='#7f95a4';ctx.strokeStyle='#d9e9f1';ctx.lineWidth=1.1;const podY=hull>=4?-.05:.08;for(const side of [-1,1]){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(side*z*(.75+hull*.035)-z*.12,z*podY,z*.24,z*(.72+hull*.035),z*.07);else ctx.rect(side*z*(.75+hull*.035)-z*.12,z*podY,z*.24,z*(.72+hull*.035));ctx.fill();ctx.stroke()}}
  ctx.fillStyle=body;ctx.strokeStyle='#edf9ff';ctx.lineWidth=1.25;ctx.beginPath();shapes[hull].forEach(([px,py],i)=>i?ctx.lineTo(px*z,py*z):ctx.moveTo(px*z,py*z));ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=dark;ctx.beginPath();ctx.moveTo(0,-z*(.9+hull*.035));ctx.lineTo(z*(.16+hull*.008),-z*.22);ctx.lineTo(0,z*(.12+hull*.025));ctx.lineTo(-z*(.16+hull*.008),-z*.22);ctx.closePath();ctx.fill();if(hull>=3){ctx.strokeStyle=accent;ctx.globalAlpha=.34;ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(-z*.55,z*.18);ctx.lineTo(-z*.22,-z*.55);ctx.moveTo(z*.55,z*.18);ctx.lineTo(z*.22,-z*.55);ctx.stroke();ctx.globalAlpha=1}
  mounts.slice(0,12).forEach((id,i)=>{const w=R.WEAPONS?.find(q=>q.id===id),side=i%2?1:-1,row=i/2|0,maxRow=Math.min(4,row),px=side*z*(.43+maxRow*.075+hull*.025),py=-z*.46+maxRow*z*.26,target=targets[i],a=target&&Number.isFinite(target.x)&&Number.isFinite(target.y)?Math.atan2(target.y-(cy+py),target.x-(cx+px)):-Math.PI/2;ctx.save();ctx.translate(px,py);ctx.fillStyle='#dbe7ed';ctx.strokeStyle='#10202a';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,z*.105,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.rotate(a);ctx.fillStyle=w?.color||accent;ctx.fillRect(0,-z*.025,z*.30,z*.05);ctx.fillStyle='#eef8fc';ctx.fillRect(z*.22,-z*.038,z*.13,z*.076);ctx.restore()});ctx.restore();
  if(opt.shield!==false){ctx.save();ctx.globalAlpha=.085+.02*Math.sin(t*1.8);ctx.strokeStyle=accent;ctx.lineWidth=1.35;ctx.beginPath();ctx.ellipse(cx,cy,z*(1.36+hull*.07),z*(1.62+hull*.045),0,0,Math.PI*2);ctx.stroke();ctx.restore()}
  drones.forEach((id,i)=>{const a=t*.62+i/Math.max(1,drones.length)*Math.PI*2,r=z*(1.55+hull*.055),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.68;ctx.fillStyle=R.droneColor?.(R.DRONES?.find(d=>d.id===id))||accent;ctx.beginPath();ctx.arc(x,y,Math.max(2.5,z*.075),0,Math.PI*2);ctx.fill()});supports.forEach((id,i)=>{const side=i%2?1:-1,row=i/2|0,bob=Math.sin(t*1.3+i)*3,x=cx+side*z*(1.9+row*.35),y=cy+z*(.65+row*.3)+bob,ss=Math.max(5,z*.18);ctx.strokeStyle='#c8dce7';ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(x,y-ss);ctx.lineTo(x+ss*.72,y+ss);ctx.lineTo(x-ss*.72,y+ss);ctx.closePath();ctx.stroke()});
};
R.drawFlagshipDisplay=R.v97DrawFlagship;
R.drawShip=function(ctx,cx,cy,scale=1,weapons=[],tier=0,preview=false,state={}){const save={hull:Number.isFinite(+tier)?+tier:0,weaponMounts:[...(weapons||[])],equippedDrones:preview?[...(state.drones||[])]:[],equippedSupports:preview?[...(state.supports||[])]:[]};return R.v97DrawFlagship(ctx,cx,cy,scale,save,{t:performance.now()/1000,shield:preview||((Number(state.shield)||0)>0),hp:state.hp,weaponTargets:state.weaponTargets||[]})};

const segEllipse=(x0,y0,x1,y1,cx,cy,rx,ry)=>{const sx=(x0-cx)/rx,sy=(y0-cy)/ry,ex=(x1-cx)/rx,ey=(y1-cy)/ry,dx=ex-sx,dy=ey-sy;if(sx*sx+sy*sy<=1)return{x:x0,y:y0,t:0};const A=dx*dx+dy*dy,B=2*(sx*dx+sy*dy),C=sx*sx+sy*sy-1,D=B*B-4*A*C;if(A<1e-8||D<0)return null;const q=Math.sqrt(D),t1=(-B-q)/(2*A),t2=(-B+q)/(2*A),t=t1>=0&&t1<=1?t1:t2>=0&&t2<=1?t2:null;return t==null?null:{x:x0+(x1-x0)*t,y:y0+(y1-y0)*t,t}};
GP.v97ShipContact=function(shield=true,pad=0){const hull=clamp(this.s?.hull|0,0,6),scale=1+hull*.11,z=34*scale;return shield?{rx:z*(1.36+hull*.07)+pad,ry:z*(1.62+hull*.045)+pad}:{rx:z*(.72+hull*.09)+pad,ry:z*(1.18+hull*.09)+pad}};
const hitShip97=GP.hitShip;
GP.hitShip=function(d,x=this.cx,y=this.cy){const beforeSh=Number(this.shield)||0,beforeHp=Number(this.hp)||0,out=hitShip97.call(this,d,x,y),afterSh=Number(this.shield)||0,afterHp=Number(this.hp)||0;if(beforeSh>afterSh){this._v97ShieldHits=this._v97ShieldHits||[];this._v97ShieldHits.push({dx:x-this.cx,dy:y-this.cy,life:.42,max:.42,seed:Math.random()*10})}if(beforeHp>afterHp){this._v97HullHits=this._v97HullHits||[];this._v97HullHits.push({dx:x-this.cx,dy:y-this.cy,life:.36,max:.36,seed:Math.random()*10})}return out};
const projectiles97=GP.projectiles;
GP.projectiles=function(dt){const hostile=this.bad||[];this.bad=[];projectiles97.call(this,dt);this.bad=hostile;for(const p of this.bad){if(!p||p.life<=0)continue;if(p.homing){const a=Math.atan2(this.cy-p.y,this.cx-p.x),sp=Math.hypot(p.vx,p.vy)||1;p.vx+=(Math.cos(a)*sp-p.vx)*dt*.8;p.vy+=(Math.sin(a)*sp-p.vy)*dt*.8}const x0=p.x,y0=p.y,x1=x0+p.vx*dt,y1=y0+p.vy*dt;p.life-=dt;if(this.mods.pd>0&&Math.random()<this.mods.pd*dt*2){p.life=0;continue}const pad=(p.r||2.5)*.65;if(this.shield>0){const q=this.v97ShipContact(true,pad),hit=segEllipse(x0,y0,x1,y1,this.cx,this.cy,q.rx,q.ry);if(hit){p.x=hit.x;p.y=hit.y;this.hitShip(p.damage,hit.x,hit.y);p.life=0;continue}}else{const q=this.v97ShipContact(false,pad),hit=segEllipse(x0,y0,x1,y1,this.cx,this.cy,q.rx,q.ry);if(hit){p.x=hit.x;p.y=hit.y;this.hitShip(p.damage,hit.x,hit.y);p.life=0;continue}}p.x=x1;p.y=y1}this.bad=this.bad.filter(p=>p&&p.life>0&&p.x>-110&&p.x<this.w+110&&p.y>-110&&p.y<this.hgt+110)};

const update97=GP.update;
GP.update=function(dt){const enc=this._v8Encounter,field=enc?.type==='asteroid'&&enc.v97===true,before=field?[...(this.rocks||[])]:null;if(field)enc.type='asteroid97';try{update97.call(this,dt)}finally{if(field&&this._v8Encounter===enc)enc.type='asteroid'}for(const a of this._v97ShieldHits||[])a.life-=dt;this._v97ShieldHits=(this._v97ShieldHits||[]).filter(a=>a.life>0);for(const a of this._v97HullHits||[])a.life-=dt;this._v97HullHits=(this._v97HullHits||[]).filter(a=>a.life>0);if(!field||this.dead||this.paused||this._v8Encounter!==enc)return;this.en=[];this.bad=[];this.tele=[];this.active=true;this.count=999;enc.spawnCooldown=(enc.spawnCooldown||0)-dt;const liveParents=(this.rocks||[]).filter(r=>r._v97Parent&&!r.dead).length;if(enc.remaining>0&&enc.spawnCooldown<=0&&liveParents<enc.activeCap){this.v97SpawnFieldRock();enc.spawnCooldown=.42+Math.random()*.48}const gone=(before||[]).filter(r=>!(this.rocks||[]).includes(r));for(const r of gone){if((r.dead||r.hp<=0)&&(r._v8Size||1)>1&&!r._v8Split){r._v8Split=true;const childSize=(r._v8Size||2)-1,baseA=Math.atan2(r.vy||0,r.vx||1),baseS=Math.max(35,Math.hypot(r.vx||0,r.vy||0));for(let i=0;i<2;i++){const c=this._v8MakeRock(childSize,r.rich,r.x+(i?5:-5),r.y),a=baseA+(i?1:-1)*(.35+Math.random()*.22),s=baseS*(.72+Math.random()*.18);c.vx=(r.vx||0)*.48+Math.cos(a)*s*.72;c.vy=(r.vy||0)*.48+Math.sin(a)*s*.72;c.value=Math.max(8,Math.round((r.value||40)*.35));c._v97Field=true;c._v97Entered=true;c._v97Parent=false;this.rocks.push(c)}}}const rocks=this.rocks||[],top=86,bottom=this.hgt-72;for(const r of rocks){if(!r._v97Entered&&r.x>=r.r+4&&r.x<=this.w-r.r-4&&r.y>=top+r.r&&r.y<=bottom-r.r)r._v97Entered=true;if(r._v97Entered){if(r.x<r.r+6){r.x=r.r+6;r.vx=Math.abs(r.vx)}else if(r.x>this.w-r.r-6){r.x=this.w-r.r-6;r.vx=-Math.abs(r.vx)}if(r.y<top+r.r){r.y=top+r.r;r.vy=Math.abs(r.vy)}else if(r.y>bottom-r.r){r.y=bottom-r.r;r.vy=-Math.abs(r.vy)}const dx=r.x-this.cx,dy=r.y-this.cy,d=Math.hypot(dx,dy)||1,min=r.r+this.v97ShipContact(false).rx*.55;if(d<min){const nx=dx/d,ny=dy/d;r.x=this.cx+nx*min;r.y=this.cy+ny*min;const dot=r.vx*nx+r.vy*ny;if(dot<0){r.vx-=1.8*dot*nx;r.vy-=1.8*dot*ny}}}}for(let i=0;i<rocks.length;i++)for(let j=i+1;j<rocks.length;j++){const a=rocks[i],b=rocks[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,min=a.r+b.r+2;if(d<min){const nx=dx/d,ny=dy/d,over=min-d;a.x-=nx*over*.5;a.y-=ny*over*.5;b.x+=nx*over*.5;b.y+=ny*over*.5;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const imp=-rel*.86;a.vx-=imp*nx;a.vy-=imp*ny;b.vx+=imp*nx;b.vy+=imp*ny}}}if(enc.remaining<=0&&rocks.length===0){enc.complete=true;this._v8FinishEncounter?.()}};
GP.v97DrawBracket=function(ctx,t,manual=false){if(!t||!Number.isFinite(t.x)||!Number.isFinite(t.y))return;const raw=t.parentBoss?12:(t.r||t.size||18),r=clamp(raw+8,15,t.boss?58:34),c=manual?'rgba(231,251,255,.96)':'rgba(116,218,245,.42)',L=manual?9:7,pulse=manual?1+Math.sin((this.t||0)*7)*.08:1;ctx.save();ctx.translate(t.x,t.y);ctx.scale(pulse,pulse);ctx.strokeStyle=c;ctx.lineWidth=manual?1.8:1.15;ctx.beginPath();ctx.moveTo(-r+L,-r);ctx.lineTo(-r,-r);ctx.lineTo(-r,-r+L);ctx.moveTo(r-L,-r);ctx.lineTo(r,-r);ctx.lineTo(r,-r+L);ctx.moveTo(-r,r-L);ctx.lineTo(-r,r);ctx.lineTo(-r+L,r);ctx.moveTo(r-L,r);ctx.lineTo(r,r);ctx.lineTo(r,r-L);ctx.stroke();if(manual){ctx.globalAlpha=.72;ctx.beginPath();ctx.arc(0,0,3.2,0,Math.PI*2);ctx.stroke()}ctx.restore()};
const draw97=GP.draw;
GP.draw=function(){draw97.call(this);const ctx=this.x;if(!ctx)return;const claimed=new Set();for(const t of this.weaponTargets||[])if(t&&this.validTarget?.(t))claimed.add(t);for(const t of claimed)if(t!==this.priority)this.v97DrawBracket(ctx,t,false);if(this.priority&&this.validTarget?.(this.priority))this.v97DrawBracket(ctx,this.priority,true);for(const h of this._v97ShieldHits||[]){const p=1-h.life/h.max,x=this.cx+h.dx,y=this.cy+h.dy;ctx.save();ctx.globalAlpha=clamp(h.life/h.max,0,1);ctx.strokeStyle='#75e7ff';ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(x,y,5+p*18,0,Math.PI*2);ctx.stroke();ctx.globalAlpha*=.55;ctx.beginPath();ctx.arc(x,y,2+p*9,0,Math.PI*2);ctx.stroke();ctx.restore()}for(const h of this._v97HullHits||[]){const p=1-h.life/h.max,x=this.cx+h.dx,y=this.cy+h.dy;ctx.save();ctx.globalAlpha=clamp(h.life/h.max,0,1);ctx.fillStyle='#ffb078';ctx.beginPath();ctx.arc(x,y,3.5+(1-p)*3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffd8a8';ctx.lineWidth=1.4;for(let i=0;i<5;i++){const a=h.seed+i*1.256,s=5+p*12;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(a)*s,y+Math.sin(a)*s);ctx.stroke()}ctx.restore()}};

GP.v97SpawnFieldRock=function(){const e=this._v8Encounter;if(!e||e.type!=='asteroid'||!e.v97||e.remaining<=0)return null;const size=e.pattern==='heavy'?(Math.random()<.62?3:2):(Math.random()<.26?3:2),rich=Math.random()<.20,rock=this._v8MakeRock?.(size,rich);if(!rock)return null;const sides=['left','right','top','bottom'];let side;if(e.pattern==='belt')side=e.beltSide;else if(e.pattern==='cross')side=(e.spawned++%2)?e.cross[0]:e.cross[1];else side=sides[Math.random()*sides.length|0];const pad=rock.r+22,speed=(e.pattern==='heavy'?42:58)+Math.random()*(e.pattern==='heavy'?24:42),yMin=118+rock.r,yMax=Math.max(yMin+20,this.hgt-108-rock.r),xMin=rock.r+24,xMax=Math.max(xMin+20,this.w-rock.r-24);if(side==='left'){rock.x=-pad;rock.y=yMin+Math.random()*(yMax-yMin);rock.vx=speed;rock.vy=(Math.random()-.5)*(e.pattern==='belt'?18:46)}else if(side==='right'){rock.x=this.w+pad;rock.y=yMin+Math.random()*(yMax-yMin);rock.vx=-speed;rock.vy=(Math.random()-.5)*(e.pattern==='belt'?18:46)}else if(side==='top'){rock.x=xMin+Math.random()*(xMax-xMin);rock.y=-pad;rock.vx=(Math.random()-.5)*(e.pattern==='belt'?18:46);rock.vy=speed}else{rock.x=xMin+Math.random()*(xMax-xMin);rock.y=this.hgt+pad;rock.vx=(Math.random()-.5)*(e.pattern==='belt'?18:46);rock.vy=-speed}rock._v97Field=true;rock._v97Parent=true;rock._v97Entered=false;rock._v8Split=false;e.remaining--;this.rocks.push(rock);return rock};
GP._v8BeginAsteroids=function(wave,sector){this._v8Encounter={type:'asteroid-intro',wave,sector,complete:false};this.en=[];this.bad=[];this.tele=[];this.rocks=[];this.active=true;this.count=999;this.paused=true;this.v83SetWaveHUD?.(wave,sector,'RESOURCE FIELD');document.querySelector('#v92FieldTimer')?.remove();const roll=Math.random(),pattern=roll<.46?'belt':roll<.72?'scatter':roll<.9?'cross':'heavy',side=['left','right','top','bottom'][Math.random()*4|0],op={left:'right',right:'left',top:'bottom',bottom:'top'},title=pattern==='belt'?'ASTEROID BELT':pattern==='cross'?'CROSSING FIELD':pattern==='heavy'?'HEAVY ASTEROIDS':'ASTEROID FIELD';this.v83Warning?.({kicker:'SENSOR // RESOURCE CONTACT',title,sub:'MOVING SALVAGE SIGNATURES DETECTED',color:'#8fc7d9'},()=>{const tier=Math.max(0,Math.floor((wave-1)/10)),total=6+Math.min(5,tier+Math.floor(wave/18)),cap=Math.min(8,4+Math.floor(tier/2));this.paused=false;this._v8Encounter={type:'asteroid',wave,sector,complete:false,v97:true,pattern,beltSide:side,cross:[side,op[side]],spawned:0,remaining:total,activeCap:cap,spawnCooldown:0};this.en=[];this.bad=[];this.tele=[];this.rocks=[];this.active=true;this.count=999;this.v97SpawnFieldRock();this.v97SpawnFieldRock()})};

const sync97=()=>{R.VERSION='0.9.7';if(R.app?.s){R.app.s.version='0.9.7';try{R.save?.(R.app.s)}catch{}}if(!document.body)return;const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))if(n.nodeValue&&/0\.9\.[0-6]/.test(n.nodeValue))n.nodeValue=n.nodeValue.replace(/0\.9\.[0-6]/g,'0.9.7')};
const main97=AP.main;if(main97)AP.main=function(...args){const out=main97.apply(this,args);requestAnimationFrame(sync97);return out};const station97=AP.station;if(station97)AP.station=function(...args){const out=station97.apply(this,args);requestAnimationFrame(sync97);return out};requestAnimationFrame(sync97);setTimeout(sync97,160);
})();