(()=>{
'use strict';
const R=window.SR;if(!R?.App||!R?.Game)return;
R.VERSION='0.9.3';
const AP=R.App.prototype,GP=R.Game.prototype,$=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const E=(t,c,h)=>{const e=document.createElement(t);if(c)e.className=c;if(h!=null)e.innerHTML=h;return e};
const fmt=n=>{n=Math.max(0,Math.round(Number(n)||0));return n<1000?String(n):n<1e6?(n/1000).toFixed(n<10000?1:0)+'k':(n/1e6).toFixed(1)+'m'};
const saveSettings=a=>{try{R.save?.(a.s)}catch{}};

const migrate93=R.migrate;
R.migrate=s=>{s=migrate93(s);if(!s)return s;s.version='0.9.3';s.settings=Object.assign({audio:1,motion:true,haptics:true},s.settings||{});return s};
const sync93=()=>{R.VERSION='0.9.3';if(R.app?.s){R.app.s=R.migrate(R.app.s);R.app.s.version='0.9.3';try{R.save?.(R.app.s)}catch{}}if(!document.body)return;const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))if(n.nodeValue&&/0\.9\.[0-2]/.test(n.nodeValue))n.nodeValue=n.nodeValue.replace(/0\.9\.[0-2]/g,'0.9.3')};

R.drawFlagshipDisplay=function(ctx,cx,cy,scale,save={},opt={}){
  const hull=clamp(save.hull|0,0,6),mounts=(save.weaponMounts||save.weapons||[]).filter(Boolean),drones=save.equippedDrones||save.drones||[],supports=save.equippedSupports||save.supports||[],t=opt.t||0;
  const z=34*scale,accent=opt.accent||'#75ddf7',body=opt.body||'#b9c8d4',dark='#12232e';
  const shapes=[[[0,-1.18],[.43,-.32],[.68,.48],[.28,.82],[0,.61],[-.28,.82],[-.68,.48],[-.43,-.32]],[[0,-1.24],[.56,-.48],[.82,.42],[.48,.76],[.22,.68],[0,.88],[-.22,.68],[-.48,.76],[-.82,.42],[-.56,-.48]],[[0,-1.24],[.48,-.73],[.9,-.12],[.88,.56],[.45,.82],[.16,.66],[0,.94],[-.16,.66],[-.45,.82],[-.88,.56],[-.9,-.12],[-.48,-.73]],[[0,-1.42],[.45,-.88],[.94,-.28],[1,.42],[.62,.8],[.27,.7],[0,1.02],[-.27,.7],[-.62,.8],[-1,.42],[-.94,-.28],[-.45,-.88]],[[0,-1.52],[.42,-1.02],[.88,-.58],[1.08,.1],[.94,.64],[.48,.92],[.18,.77],[0,1.1],[-.18,.77],[-.48,.92],[-.94,.64],[-1.08,.1],[-.88,-.58],[-.42,-1.02]],[[0,-1.62],[.48,-1.16],[.98,-.68],[1.16,-.02],[1.02,.66],[.58,.96],[.24,.82],[0,1.17],[-.24,.82],[-.58,.96],[-1.02,.66],[-1.16,-.02],[-.98,-.68],[-.48,-1.16]],[[0,-1.72],[.55,-1.28],[1.05,-.8],[1.24,-.16],[1.18,.54],[.76,.93],[.34,.86],[0,1.24],[-.34,.86],[-.76,.93],[-1.18,.54],[-1.24,-.16],[-1.05,-.8],[-.55,-1.28]]];
  ctx.save();ctx.translate(cx,cy);const engines=hull<2?2:hull<5?3:4;for(let i=0;i<engines;i++){const off=(i-(engines-1)/2)*z*.25,flame=z*(.52+.11*Math.sin(t*5+i));ctx.globalAlpha=.16+.07*Math.sin(t*4+i);ctx.fillStyle=accent;ctx.beginPath();ctx.moveTo(off-z*.08,z*.7);ctx.lineTo(off,z*.7+flame);ctx.lineTo(off+z*.08,z*.7);ctx.fill()}ctx.globalAlpha=1;
  if(hull>=2){ctx.fillStyle='#7f95a4';ctx.strokeStyle='#d9e9f1';ctx.lineWidth=1.1;const podY=hull>=4?-.05:.08;for(const side of [-1,1]){ctx.beginPath();ctx.roundRect?.(side*z*(.75+hull*.035)-z*.12,z*podY,z*.24,z*(.72+hull*.035),z*.07);ctx.fill();ctx.stroke()}}
  ctx.fillStyle=body;ctx.strokeStyle='#edf9ff';ctx.lineWidth=1.25;ctx.beginPath();shapes[hull].forEach(([px,py],i)=>i?ctx.lineTo(px*z,py*z):ctx.moveTo(px*z,py*z));ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=dark;ctx.beginPath();ctx.moveTo(0,-z*(.9+hull*.035));ctx.lineTo(z*(.16+hull*.008),-z*.22);ctx.lineTo(0,z*(.12+hull*.025));ctx.lineTo(-z*(.16+hull*.008),-z*.22);ctx.closePath();ctx.fill();if(hull>=3){ctx.strokeStyle=accent;ctx.globalAlpha=.34;ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(-z*.55,z*.18);ctx.lineTo(-z*.22,-z*.55);ctx.moveTo(z*.55,z*.18);ctx.lineTo(z*.22,-z*.55);ctx.stroke();ctx.globalAlpha=1}
  mounts.forEach((id,i)=>{const w=R.WEAPONS?.find(q=>q.id===id),side=i%2?1:-1,row=i/2|0,maxRow=Math.min(4,row),px=side*z*(.43+maxRow*.075+hull*.025),py=-z*.46+maxRow*z*.26;ctx.save();ctx.translate(px,py);ctx.fillStyle='#dbe7ed';ctx.strokeStyle='#10202a';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,z*.105,0,7);ctx.fill();ctx.stroke();ctx.fillStyle=w?.color||accent;ctx.fillRect(-z*.02,-z*.23,z*.04,z*.24);ctx.restore()});ctx.restore();
  if(opt.shield!==false){ctx.save();ctx.globalAlpha=.10+.025*Math.sin(t*1.8);ctx.strokeStyle=accent;ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(cx,cy,z*(1.36+hull*.07),z*(1.62+hull*.045),0,0,7);ctx.stroke();ctx.restore()}
  drones.forEach((id,i)=>{const a=t*.62+i/Math.max(1,drones.length)*Math.PI*2,r=z*(1.55+hull*.055),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r*.68;ctx.fillStyle=R.droneColor?.(R.DRONES?.find(d=>d.id===id))||accent;ctx.beginPath();ctx.arc(x,y,Math.max(2.5,z*.075),0,7);ctx.fill()});supports.forEach((id,i)=>{const side=i%2?1:-1,row=i/2|0,bob=Math.sin(t*1.3+i)*3,x=cx+side*z*(1.9+row*.35),y=cy+z*(.65+row*.3)+bob,ss=Math.max(5,z*.18);ctx.strokeStyle='#c8dce7';ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(x,y-ss);ctx.lineTo(x+ss*.72,y+ss);ctx.lineTo(x-ss*.72,y+ss);ctx.closePath();ctx.stroke()})
};

AP.v93AnimateShipPage=function(){cancelAnimationFrame(this._v92ShipAnim||0);cancelAnimationFrame(this._v93ShipAnim||0);const cv=$('#ship');if(!cv)return;const x=cv.getContext('2d'),stars=Array.from({length:95},()=>({x:Math.random()*cv.width,y:Math.random()*cv.height,z:.25+Math.random()*1.7}));let t=0;const frame=()=>{if(!cv.isConnected)return;t+=.016;const s=this.s;x.clearRect(0,0,cv.width,cv.height);const g=x.createLinearGradient(0,0,0,cv.height);g.addColorStop(0,'#07131c');g.addColorStop(.58,'#02080d');g.addColorStop(1,'#050a0e');x.fillStyle=g;x.fillRect(0,0,cv.width,cv.height);for(const q of stars){q.y+=q.z*.22;if(q.y>cv.height){q.y=0;q.x=Math.random()*cv.width}x.fillStyle=`rgba(201,232,243,${.07+q.z*.14})`;x.fillRect(q.x,q.y,q.z>1.2?2:1,q.z>1.2?3:1)}x.strokeStyle='rgba(85,166,194,.12)';x.lineWidth=2;for(const sx of [70,138,cv.width-138,cv.width-70]){x.beginPath();x.moveTo(sx,0);x.lineTo(sx+(sx<cv.width/2?72:-72),cv.height);x.stroke()}for(let i=0;i<6;i++){const pulse=.12+.13*Math.max(0,Math.sin(t*2.2+i*.8));x.fillStyle=`rgba(89,220,249,${pulse})`;x.fillRect(42+i*(cv.width-84)/5,cv.height-26,34,3)}const scan=(t*.11%1)*cv.height;x.fillStyle='rgba(102,222,250,.045)';x.fillRect(0,scan,cv.width,2);const bob=Math.sin(t*1.2)*4;R.drawFlagshipDisplay(x,cv.width/2,cv.height*.52+bob,2.05,s,{t,shield:true});this._v93ShipAnim=requestAnimationFrame(frame)};frame()};
const ship93=AP.tab_ship;AP.tab_ship=function(c){const out=ship93.call(this,c);requestAnimationFrame(()=>{this.v93AnimateShipPage();c.classList.add('v93BootIn')});return out};

const startMain92=AP.v92StartMain;AP.v92StartMain=function(){startMain92.call(this);cancelAnimationFrame(this._v92MainAnim||0);const bg=$('#v92MainScene'),live=$('.v83MainShip'),diag=$('#v92MainDiag');if(!bg)return;const stars=Array.from({length:125},()=>({x:Math.random(),y:Math.random(),z:.25+Math.random()*1.75}));let t=0;document.querySelectorAll('body.v92Main .screen button').forEach((b,i)=>{b.style.setProperty('--v93i',i);b.classList.add('v93MenuEntry')});diag?.classList.add('v93DiagLive');const frame=()=>{if(!document.body.classList.contains('v92Main')||!bg.isConnected)return;const dpr=Math.min(2,devicePixelRatio||1),w=innerWidth,h=innerHeight;if(bg.width!==Math.round(w*dpr)||bg.height!==Math.round(h*dpr)){bg.width=Math.round(w*dpr);bg.height=Math.round(h*dpr);bg.style.width=w+'px';bg.style.height=h+'px'}const x=bg.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.fillStyle='#02050a';x.fillRect(0,0,w,h);t+=.016;const halo=x.createRadialGradient(w*.5,h*.27,0,w*.5,h*.27,w*.55);halo.addColorStop(0,'rgba(26,82,105,.22)');halo.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=halo;x.fillRect(0,0,w,h);for(const q of stars){q.y+=q.z*.00062;if(q.y>1){q.y=0;q.x=Math.random()}x.fillStyle=`rgba(214,239,248,${.11+q.z*.18})`;x.fillRect(q.x*w,q.y*h,q.z>1.25?1.6:1,q.z>1.35?2.8:1)}const rr=Math.min(w,h)*(.27+.012*Math.sin(t*.65));x.strokeStyle='rgba(83,190,224,.05)';x.beginPath();x.arc(w*.5,h*.27,rr,0,7);x.stroke();if(live?.isConnected){const lx=live.getContext('2d'),lw=live.width,lh=live.height,s=this.s||R.getSlot?.(R.loadAll?.().last||1);lx.clearRect(0,0,lw,lh);const gl=lx.createRadialGradient(lw/2,lh*.62,0,lw/2,lh*.62,lw*.42);gl.addColorStop(0,'rgba(72,207,242,.14)');gl.addColorStop(1,'rgba(0,0,0,0)');lx.fillStyle=gl;lx.fillRect(0,0,lw,lh);R.drawFlagshipDisplay(lx,lw/2,lh*.5+Math.sin(t*1.05)*3,1.28,s,{t,shield:true})}this._v92MainAnim=requestAnimationFrame(frame)};frame()};

AP.settings=function(){this.v92StopMain?.();cancelAnimationFrame(this._v93ShipAnim||0);document.body.className='v93SettingsBody';this.s=R.migrate(this.s||R.getSlot?.(R.loadAll?.().last||1));const s=this.s,app=$('#app');if(!app||!s)return this.main?.();const audio=clamp(Number(s.settings?.audio??1),0,1),motion=s.settings?.motion!==false,haptics=s.settings?.haptics!==false,dev=new URLSearchParams(location.search).get('dev')==='1';app.innerHTML=`<main class="v93Settings"><header><button class="v93Back" data-back>‹</button><span><small>LoE</small><h1>SETTINGS</h1><b>FLAGSHIP INTERFACE</b></span><i></i></header><section class="v93SettingsGrid"><article><div><small>AUDIO</small><b>MASTER OUTPUT</b><p>Global volume for combat, interface, and system tones.</p></div><label class="v93Range"><input data-audio type="range" min="0" max="1" step=".05" value="${audio}"><span>${Math.round(audio*100)}%</span></label></article><article><div><small>INTERFACE</small><b>MOTION</b><p>Animated flagship feeds, scan sweeps, and interface transitions.</p></div><button class="v93Toggle ${motion?'on':''}" data-motion>${motion?'ON':'OFF'}</button></article><article><div><small>DEVICE</small><b>HAPTICS</b><p>Light feedback for supported controls and selections.</p></div><button class="v93Toggle ${haptics?'on':''}" data-haptics>${haptics?'ON':'OFF'}</button></article><article><div><small>DATA</small><b>SAVE SLOTS</b><p>Load, overwrite, or manage flagship records.</p></div><button class="v93Action" data-slots>OPEN</button></article>${dev?`<article><div><small>DEVELOPER</small><b>BOSS LAB</b><p>Launch a boss directly for encounter testing.</p></div><button class="v93Action" data-boss>OPEN</button></article>`:''}</section><footer><span><i></i>SYSTEM LINK</span><b>v0.9.3</b></footer></main>`;const root=app.querySelector('.v93Settings');requestAnimationFrame(()=>root.classList.add('show'));root.querySelector('[data-back]').onclick=()=>this.main();const range=root.querySelector('[data-audio]'),read=root.querySelector('.v93Range span');range.oninput=()=>{const v=+range.value;R.audio.master=v;s.settings.audio=v;read.textContent=Math.round(v*100)+'%';saveSettings(this)};const toggle=(key,el)=>{s.settings[key]=!s.settings[key];el.classList.toggle('on',s.settings[key]);el.textContent=s.settings[key]?'ON':'OFF';saveSettings(this);if(key==='haptics'&&s.settings[key])navigator.vibrate?.(8)};root.querySelector('[data-motion]').onclick=e=>toggle('motion',e.currentTarget);root.querySelector('[data-haptics]').onclick=e=>toggle('haptics',e.currentTarget);root.querySelector('[data-slots]').onclick=()=>this.slots?.();root.querySelector('[data-boss]')?.addEventListener('click',()=>this.v92OpenBossLab?.())};

GP.v93CardsOpen=function(){const c=$('#cards');return !!(c&&(c.classList.contains('show')||c.querySelector('.card')))};GP.v93MarkBossResolved=function(){const e=this._v8Encounter;if(e?.type==='boss')e.victoryResolved=true};GP.v93MarkTraderResolved=function(){const e=this._v8Encounter;if(e?.type==='boss')e.traderResolved=true};GP.v93WaitForDraft=function(cb){clearTimeout(this._v93DraftWait);const tick=()=>{if(this.dead)return;if(this.v93CardsOpen()){this._v93DraftWait=setTimeout(tick,90);return}cb?.()};tick()};
GP.v93ShowEngineerTrader=function(){if($('#engineerTrader'))return;this.paused=true;const pool=(R.CARDS||[]).filter(c=>['legendary','mythic'].includes(c.rarity)&&!this.cards.includes(c.id)),picks=[];while(picks.length<3&&pool.length){const c=pool[Math.random()*pool.length|0];if(!picks.includes(c))picks.push(c);pool.splice(pool.indexOf(c),1)}const fee=Math.round(550+this.wave*45),o=E('div','engineerTrader v93Trader');o.id='engineerTrader';o.innerHTML=`<div class="v93TraderCard"><small>NEUTRAL CONTACT // GALACTIC ENGINEERS</small><h2>PREMIUM TECHNOLOGY</h2><p>Purchase one technology or continue the expedition.</p><div class="v93TradeChoices"></div><button class="btn quiet" data-skip>CONTINUE</button></div>`;document.body.append(o);const g=o.querySelector('.v93TradeChoices');if(!picks.length)g.innerHTML='<div class="v93NoTrade">NO NEW PREMIUM TECHNOLOGY AVAILABLE</div>';const finish=()=>{o.remove();this.v93MarkTraderResolved();this.paused=false};picks.forEach(c=>{const b=E('button',`v93Trade ${c.rarity||''}`,`<i>${c.icon||'◇'}</i><b>${c.name}</b><span>${R.RARITIES?.[c.rarity]?.name||c.rarity}</span><small>${c.desc||''}</small><em>▰ ${fmt(fee)}</em>`);b.onclick=()=>{if(this.salvage<fee){this.app?.deny?.('NEED SALVAGE');return}this.salvage-=fee;this.applyCard?.(c);finish()};g.append(b)});o.querySelector('[data-skip]').onclick=finish};GP.showEngineerTrader=function(){this.v93ShowEngineerTrader()};
GP.showBossVictory=function(){if($('#bossVictory'))return;if(this.v93CardsOpen()){if(!this._v93VictoryQueued){this._v93VictoryQueued=true;this.v93WaitForDraft(()=>{this._v93VictoryQueued=false;this.showBossVictory()})}return}this.paused=true;const missingH=1-this.hp/Math.max(1,this.maxHp),missingS=1-this.shield/Math.max(1,this.maxShield),cost=Math.max(0,Math.round((missingH*.72+missingS*.28)*(320+this.wave*38))),next=this.wave+1,color=this._v91LastBossColor||this.currentSector?.color||'#67dfff';const o=E('div','v91BossVictory v93BossVictory');o.id='bossVictory';o.style.setProperty('--accent',color);o.innerHTML=`<div class="v91VictoryCard v93VictoryCard"><small>SYSTEM // BOSS DESTROYED</small><h2>${this._v91LastBossName||'COMMAND SHIP'} DESTROYED</h2><p>NEXT SECTOR CHECKPOINT <b>WAVE ${next}</b> UNLOCKED</p><div class="v91BossStatus"><span>HULL <b>${Math.round(this.hp/Math.max(1,this.maxHp)*100)}%</b></span><span>SHIELD <b>${Math.round(this.shield/Math.max(1,this.maxShield)*100)}%</b></span><span>SALVAGE <b>▰ ${fmt(this.salvage)}</b></span></div><button class="btn primary" data-a="repair">FULL REPAIR <small>▰ ${fmt(cost)}</small></button><button class="btn" data-a="continue">CONTINUE DAMAGED</button><button class="btn quiet" data-a="return">RETURN TO STATION</button>`;document.body.append(o);requestAnimationFrame(()=>o.classList.add('show'));const continueRun=()=>{o.remove();this.v93MarkBossResolved();if(this.wave%20===0){const e=this._v8Encounter;if(e?.type==='boss')e.traderResolved=false;this.v93WaitForDraft(()=>this.v93ShowEngineerTrader())}else{this.v93MarkTraderResolved();this.paused=false}};o.querySelector('[data-a=repair]').onclick=()=>{if(this.salvage<cost){this.app?.deny?.('NEED SALVAGE');return}this.salvage-=cost;this.hp=this.maxHp;this.shield=this.maxShield;continueRun()};o.querySelector('[data-a=continue]').onclick=continueRun;o.querySelector('[data-a=return]').onclick=()=>{o.remove();this.v93MarkBossResolved();this.v93MarkTraderResolved();this.dead=true;this.paused=true;const result=this.v91RunResult?.()||{wave:this.wave,kills:this.kills,bosses:this.bosses,salvage:this.salvage,cores:this.cores,level:this.level};if(this._v91DevSession){this.app?.v91ShowReport?.(result,'success',()=>this.app.main?.());return}if(this.app){this.app._v91PendingMode='success';this.app._v91PendingMeta={level:this.level||1};this.app.finish?.(result,'success')}}};
const update93=GP.update;GP.update=function(dt){update93.call(this,dt);if(this.dead)return;const enc=this._v8Encounter;if(enc?.type==='boss'&&!enc.victoryResolved&&!$('#bossVictory')&&!this.v93CardsOpen()&&this._v91LastBossName&&!(this.en||[]).some(e=>e.boss)){this._v93BossSettle=(this._v93BossSettle||0)+dt;if(this._v93BossSettle>.55){this._v93BossSettle=0;this.showBossVictory()}}else this._v93BossSettle=0};

const main93=AP.main;AP.main=function(...args){document.body.classList.remove('v93SettingsBody','v93StationIn');R.VERSION='0.9.3';const out=main93.apply(this,args);requestAnimationFrame(()=>{sync93();document.querySelector('.screen')?.classList.add('v93ScreenIn')});return out};const station93=AP.station;AP.station=function(...args){document.body.classList.remove('v93SettingsBody');R.VERSION='0.9.3';const out=station93.apply(this,args);requestAnimationFrame(()=>{sync93();document.body.classList.add('v93StationIn');document.querySelector('.screen')?.classList.add('v93ScreenIn')});return out};const build93=GP.build;GP.build=function(...args){document.body.classList.remove('v93SettingsBody','v93StationIn');return build93.apply(this,args)};
requestAnimationFrame(sync93);setTimeout(sync93,220);
})();